@startuml

:Restart;
if (IMAGE_STATUS == NONE) then (yes)
    : reboot;
    stop
else (no)
    if (IMAGE_STATUS == DOWNLOAD) then (yes)
        if (cBSL_backup) then (success)
            :cBSL_load();
            :set IMAGE_STATUS =\nPENDING_VALIDATION;
            :reboot;
            stop
        else (failure)
            :set CBSL_STATUS\n = BACKUP_FAILURE;
            :set IMAGE_STATUS\n = NONE;
            :reboot;
            stop
        endif
    else (no)
        if (IMAGE_STATUS == PENDING_VALIDATION) (yes)
            :recover();
            :set IMAGE_STATUS =\nNONE;
            :reboot;
            stop
        else (no)
            :reboot;
            stop
        endif
    endif
endif

@enduml
