@startuml

title Custom BSL Sequences

group Upload Image

    Server -> Application: Send New Image

    note right of Application
        The Application Places
        the new image into
        the Download Region
    end note

    Application -> cBSL: Set Image Status to //DOWNLOAD//

    Application -> uC: Reset by entering a while(1) loop due to WDT timeout
end

...

group Load Downloaded Image
    note left of cBSL
        **See cBSL Activity Diagram**
    end note
end

@enduml
